---
driver:
  name: vagrant
  require_chef_omnibus: 12.1.2

provisioner:
  name: chef_zero
  environments_path: '../chef-repo/environments'
  data_bags_path: '../chef-repo/data_bags'

platforms:
  - name: centos-7.0
    driver_config:
      network:
        - ["private_network", {ip: "33.33.11.10"}]

suites:
  - name: jenkins-production
    provisioner:
      client_rb:
        environment: production
    driver:
      vm_hostname: jenkins001.local
      network:
        - ["private_network", {ip: "33.33.11.170"}]
    run_list: 'recipe[jenkins-server]'
    attributes:
      dev_mode: true
  - name: jenkins-testing
    provisioner:
      client_rb:
        environment: testing
    driver:
      vm_hostname: jenkins001.local
      network:
        - ["private_network", {ip: "33.33.13.170"}]
    run_list: 'recipe[jenkins-server]'
    attributes:
      dev_mode: true